// admin/src/pages/login.vue
<script setup lang="ts">
import type { FormInstance, FormRules } from 'element-plus'
const loginFormRef = $ref<FormInstance>()
const user = reactive({
  username: '',
  password: '',
})
const router = useRouter()
const rules = reactive<FormRules>({
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { min: 3, max: 12, message: '长度在 3 到 5 个字符', trigger: 'blur' },
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 3, max: 12, message: '长度在 3 到 12 个字符', trigger: 'blur' },
  ],
})

let loading = $ref(false)
const handleLogin = async () => {
  loginFormRef.validate(async (valid) => {
    if (valid) {
      loading = true
      try {
        await useUserStore().login(user)
        router.push('/')
      }
      catch (error) {
        // console.log(error)
      }
      loading = false
    }
    else {
      return false
    }
  })
}
</script>

<template>
  <div class="flex items-center justify-center min-h-screen p-4 bg-gray-100">
    <div class="w-1/2 bg-white rounded-md shadow-lg">
      <div class="flex flex-col items-center p-5 bg-white md:flex-1">
        <h3 class="my-4 text-2xl font-semibold text-gray-700">
          Account Login
        </h3>

        <el-form ref="loginFormRef" :model="user" :rules="rules" label-width="120px" class="flex flex-col items-center justify-centerf">
          <el-form-item class="text-black " prop="username" label="username">
            <el-input
              ref="username" v-model="user.username" placeholder="Username" name="username" type="text"
              autocomplete="on"
            />
          </el-form-item>
          <el-form-item prop="password" label="password">
            <el-input
              ref="password" v-model="user.password" placeholder="Password" name="password" type="password"
              autocomplete="on"
            />
          </el-form-item>
          <el-button type="primary" :loading="loading" @click="handleLogin">
            Login
          </el-button>
        </el-form>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
:deep(.ep-form-item__content)  {
  flex-wrap: nowrap;
  margin-left: 0;
  color: gray;
}
:deep(.ep-input__inner),
:deep(.ep-form-item__label) {
  color: gray;
}
</style>

<route lang="yaml">
meta:
  layout: blank
  hidden: true
</route>

// client/src/pages/login/index.tsx
import type { FC } from 'react'
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Form, Input, message } from 'antd'
import { useAuthDispatch, useAuthState } from '~/context/AuthContext'
import { setToken } from '~/utils/auth'
import { usePost } from '~/hooks/useFetch'
export interface ReqParams {
  username: string
  password: string
}
export interface responseData {
  token: string
  user: any
  message: string
}
const Login: FC = () => {
  const { redirectPath } = useAuthState()
  // 获取数据
  const { data, loading, fetchData } = usePost<responseData>()
  const dispatch = useAuthDispatch()
  const navigate = useNavigate()
  // 监听data，有数据证明登录成功，保存个人信息，跳转到首页
  useEffect(() => {
    if (data) {
      dispatch({ type: 'LOGIN_SUCCESS', payload: data?.user })
      setToken(data.token)
      navigate(redirectPath)
    }
  }, [data])
  const onFinish = async (values: any) => {
    fetchData('/auth/login', values)
  }

  const onFinishFailed = (errorInfo: any) => {
    message.error(errorInfo)
  }

  return (
    <div className="flex items-center justify-center min-h-screen p-4 bg-gray-100">
      <div
        className="w-3/4 bg-white rounded-md shadow-lg lg:w-1/2"
      >
        <div className="flex flex-col items-center p-5 bg-white md:flex-1">
          <h3 className="my-4 text-2xl font-semibold text-gray-700">Account Login</h3>
          <Form
            name="basic"
            labelCol={{ span: 8 }}
            wrapperCol={{ span: 16 }}
            initialValues={{ remember: true }}
            onFinish={onFinish}
            onFinishFailed={onFinishFailed}
            autoComplete="off"
          >
            <Form.Item
              label="Username"
              name="username"
              rules={[{ required: true, message: 'Please input your username!' }]}
            >
              <Input />
            </Form.Item>

            <Form.Item
              label="Password"
              name="password"
              rules={[{ required: true, message: 'Please input your password!' }]}
            >
              <Input.Password />
            </Form.Item>
            <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
              <Button loading={loading} type="primary" htmlType="submit">
                Login
              </Button>

            </Form.Item>
          </Form>
        </div>
      </div>
    </div>

  )
}

export default Login
